FROM ubuntu:18.04

RUN apt-get update -y && apt-get install -y software-properties-common && apt-add-repository -y ppa:nginx/stable && apt-get update -y && apt-get install -y nginx

RUN chown -R www-data:www-data /var/lib/nginx
RUN mkdir -p /usr/share/nginx/logs && chown -R www-data:www-data /usr/share/nginx

EXPOSE 8888

ADD ./conf/nginx-proxy.conf /etc/nginx/nginx.conf
ADD ./conf/mime.types /etc/nginx/mime.types

WORKDIR /etc/nginx

CMD ["nginx"]


